/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zion64' at '15. 12. 11 오전 1:54' with Gradle 2.9
 *
 * @author zion64, @date 15. 12. 11 오전 1:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
